language: bash

cache:
  directories:
    - $HOME/miniconda3

before_cache:
  - rm -rf $HOME/miniconda3/pkgs/cache
  - rm -rf $HOME/miniconda3/envs/hosts
  - rm -rf $HOME/miniconda3/conda-meta/history
  - touch $HOME/miniconda3/conda-meta/history

os:
  - linux
  - osx
  - windows

env:
  - PYTHON_VERSION="3.5"
  - PYTHON_VERSION="3.6"
  - PYTHON_VERSION="3.7"

before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - chmod +x ci/install_conda.sh ci/setup_conda_env.sh

install:
  - ci/install_conda.sh
  - ci/setup_conda_env.sh

script:
  - source activate hosts
  - pytest --cov=pandera tests/
  - codecov
  # Check conformity to flake8 style guide
  - flake8 pandera/pandera.py tests
  # Check docs can build, treating warnings as errors
  - make -C docs doctest && python -m sphinx -E -W "docs/source" "docs/_build"